name: API_KEY CI Pipeline
#source: https://www.codegenes.net/blog/using-github-actions-to-create-a-env-file-in-the-workflow/#method-2-using-a-dedicated-action-eg-createdotenv-action

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate .env file with create-dotenv-action  
        uses: dotenvs/create-dotenv-action@v3
        with:  
          # List of secrets to include (format: "KEY=secret_name")  
          key-value-pairs: |  
            TEST_API_KEY=TEST_API_KEY 
          env: |  
            NODE_ENV=production 
